### ISSUE TITLE
version in play store?

### ISSUE THREAD

**Issue by maks** [msarto/AVario#1]
Hi,
I noticed the apk in the play store reports the version as 1.4.32 but the in version.xml in master here is 1.4
So I was wondering if the play store version matches whats here or does it have some changes not in the  master branch here?

**Comment by msarto** [comment]
The application is versioned (on play store) with the version from
version.xml (1.4) and build (android:versionCode="33") from
AndroidManifest.xml
So it combines this for 1.4.33

The efects of changing the version (1.4) for AVario will be that the user
settings will be reset to default values, while an update with the build
number (33) will keep the original settings.
If a major change is required and the old settings are not longer appliable
then the version is increased.

2015-02-26 2:31 GMT+02:00 Maksim Lin notifications@github.com:

**Comment by maks** [comment]
My apologies I should have read the code more closely, I can see that's how the string is concatenated in Preferences.getAppVersion().
And yes that's a very good point about not resetting the user settings.
