### ISSUE TITLE
different version in google play build

### ISSUE THREAD

**Issue by maks** [msarto/AVario#3]
hi @msarto I started looking into a couple issues I ran into with the current version published on Google Play and I noticed that the versionCode on app in play is 37 whereas the version here in the master branch is 34 ?
Also I didn't spot any tags here, would you consider tagging each new release in git to make it a bit easier to track which commits are in each build that goes on Play store? Maybe even using the release feature here in Github?

**Comment by msarto** [comment]
Fixed. Version has been updated to 38 - next version.
I will start using tags. Thanks for the feedback.
